bot:
  kit:
    botUserName: arsanya_bot
    botToken: 1114025234:AAHR0RRhLdNCHjAQd6BaA9Nl48LWkDM_pvc
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kit_bot
    driverclassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform=org: hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  liquibase:
    change-log: classpath:db/data.xml
