 version: '3.7'

 services:
      kit_db_postgres:
        build:
          context: db
          dockerfile: Dockerfile
        volumes:
          - db-data:/var/lib/postgresql/data
        container_name: tg_bot_kit_db
        env_file:
          - ./app-variables.env
        ports:
          - "5434:5432"
        restart: "unless-stopped"

 volumes:
  db-data:

